alias: Bedroom_morning_routine_weekday
description: ""
triggers:
  - platform: time
    at: "06:00:00"
conditions:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
actions:
  - service: light.turn_on
    data:
      transition: 300
      rgb_color:
        - 255
        - 136
        - 0
      brightness_pct: 75
    target:
      entity_id: light.master_bed_lamps
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: media_player.volume_set
    target:
      entity_id: media_player.echodot
    data:
      volume_level: 0.2
  - service: notify.alexa_media_echodot
    data:
      message: >-
        Good Morning. Today will be {{
        states('sensor.home_condition_day_0') }}. It will feel like {{
        states('sensor.home_realfeel_temperature_max_day_0') | float | round(0)
        }} degrees, and cool down to {{
        states('sensor.home_realfeel_temperature_min_day_0') | float | round(0)
        }} degrees.
  - wait_template: "{{ is_state('media_player.echodot', 'playing') }}"
    timeout: 10
  - wait_template: "{{ not is_state('media_player.echodot', 'playing') }}"
    timeout: 60
  - delay:
      seconds: 2
  - service: spotifyplus.player_transfer_playback
    data:
      entity_id: media_player.spotifyplus_user
      device_id: "echodot"
      play: false
  - service: media_player.play_media
    target:
      entity_id: media_player.spotifyplus_user
    data:
      media_content_type: playlist
      media_content_id: spotify:playlist:1o3dz2CJ6WRxn42itt85V0
  - service: media_player.shuffle_set
    target:
      entity_id: media_player.spotifyplus_user
    data:
      shuffle: true
  - service: media_player.media_next_track
    target:
      entity_id: media_player.spotifyplus_user
  - service: light.turn_on
    data:
      transition: 300
      rgb_color:
        - 255
        - 198
        - 77
      brightness_pct: 100
    target:
      entity_id: light.master_bed_lamps
  - delay:
      hours: 0
      minutes: 45
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    data:
      transition: 300
    target:
      entity_id: light.master_bed_lamps
  - service: media_player.media_stop
    data: {}
    target:
      entity_id: media_player.echodot
mode: single
